### ISSUE TITLE
_array_data.array_id is not a component of the key of _array_data

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/imgCIF#5]
The dictionary currently states that `_array_data.array_id` and `_array_data.binary_id` are the key data names of the `array_data` category. Using `array_id` in the key is pointless as the `array_id` will be unique for any given image/binary_id, in other words, it is not possible to have different `array_id`s with the same `binary_id` as is implied by having both data names participate in the key. `_array_data.binary_id` alone is sufficient to identify any row in this category and should be the only data name in the key.

**Comment by yayahjb** [comment]
"The value of _array_data.binary_id distinguishes among multiple sets of data with the same array structure."

There is no reason we cannot have two distinct blocks of data with the same binary_id and two different array_id.

There is no basis for the assertion that "it is not possible to have different array_ids with the same binary_id"

We should _never_ remove components of a composite key.  The most we can do is to make a component implicit, but array_id is already implicit.

**Comment by yayahjb** [comment]
This is incorrect.  This is intentionally a composite key.  We cannot ever
remove a component from a composite key.  There is no basis for the
assertion that " the array_id will be unique for any given
image/binary_id".  The most we can do is make a component implicit, but
that has already been done.
DDL2 support implicit.  The correct solution for this issue is to permit
implicit in DDLm, not to break an existing capability in imgCIF.

**Comment by jamesrhester** [comment]
Clearly I have an incorrect mental model. My understanding was that a binary id is attached to a particular array of binary data, and that this uniquely identifies the data.  I had therefore understood that array_id provides a link to the information on how to decode and structure the image, so for any given image this would be a unique value as there could be only one way to decode it.

However, as per @yayahjb 's comment, it is actually intended that there could be distinct binary data chunks with the same binary id.  These will _necessarily_ have different array ids (because we have a composite key) and so would normally come from a different detector. So I believe that the real-world mental model is that different detectors, with possibly different axis names and possibly different encoding schemes, can comfortably generate binary ids independently of one another without any concern that there will be a collision of binary_id values.

This parallels the behaviour of the scan/frame duo, where frame ids can be duplicated but the scan+frame combination must be unique.

@yayahjb : have I understood the intention correctly? If so I will close this and #6  and make a mental note to check that Vol G is clear on this.

**Comment by yayahjb** [comment]
It is actually a bit more complex than that, because the same diffraction
image information can co-exist in multiple array structures in the same
dataset
now that a given detector (such as the Eiger) can provide multiple
presentations of the same data (e.g.Eiger FileWritier versus Eiger
Stream).  The only restriction is that there is a composite key:
{array_id, binary_id} that can be used to retrieve an image.
